# Generated by Django 5.2.14 on 2026-05-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_quoterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='description',
        ),
    ]
